### ISSUE TITLE
"yaml view" should stop on invalid files

### ISSUE THREAD

**Issue by indeyets** [rubyunworks/yaml_command#5]
I can specify any text file as parameter to `yaml view` and it will just output it as-is, occasionally colouring lines which look like pieces of yaml

Is that intentional? I expected that it would give me something along the lines of "this file does not look like a valid YAML file"

**Comment by trans** [comment]
Good idea. 

At this point the `view` code is very simplistic. It was a quick hack just to have something for it. Ultimately I want to make it more advanced, with features like color-coordinating anchors and references.

Also, adding a `yaml lint` command would be a good idea. But I'm not sure how to go about implementing that.
