### ISSUE TITLE
Minor typos in README.md

### ISSUE THREAD

**Issue by baxter-brad** [rubyunworks/yaml_command#6]
Re: README.md

splat 
The splat command take a YAML file and converts it into a file directory structure. It is essentially the opposite of slurp.

[Change "take" to "takes".]

Ruby Interpreter

The yaml command is a Ruby script, so you will need a Ruby interpreter installed on your system. There are a few of these now, such as Rubinius, JRuby and the original MRI. The later is the typical choice, and usually can be installed via your operating system's package manager. For example, on dpkg-based systems like Ubuntu, you can type in a shell console:

[Change "later" to "latter".]

Copyrights

Copyright (c) 2011 Rubyworks. All rights reserved.

[Change "2011" to "2013"?]

**Comment by trans** [comment]
Thanks! All fixed, except (c) 2011 --the very first rendition of this project was created in Oct. of 2011.
